package org.mybatis.extend.demo.service.account;

import org.mybatis.extend.demo.model.account.AdminAccount;
import org.mybatis.extend.generic.service.GenericService;

/**
* Service: AdminAccountService
* Mapper : AdminAccountMapper
* Model  : AdminAccount
*
* This Service generated by MyBatis Generator Extend at 2017-02-25 18:36:04
*/
public interface AdminAccountService extends GenericService<AdminAccount, Integer> {
}