package org.mybatis.extend.demo.mapper.role;

import org.mybatis.extend.demo.model.role.AdminRole;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
* Mapper: AdminRoleMapper
* Model : AdminRole
* Table : admin_role
*
* This Mapper generated by MyBatis Generator Extend at 2017-02-25 18:36:04
*/
public interface AdminRoleMapper extends GenericMapper<AdminRole, Integer> {
}