package org.mybatis.extend.demo.service.role;

import org.mybatis.extend.demo.model.role.AdminRole;
import org.mybatis.extend.generic.service.GenericService;

/**
* Service: AdminRoleService
* Mapper : AdminRoleMapper
* Model  : AdminRole
*
* This Service generated by MyBatis Generator Extend at 2017-02-25 18:36:04
*/
public interface AdminRoleService extends GenericService<AdminRole, Integer> {
}