package org.mybatis.extend.demo.mapper.account;

import org.mybatis.extend.demo.model.account.AdminAccount;
import org.mybatis.extend.generic.mapper.GenericMapper;

/**
* Mapper: AdminAccountMapper
* Model : AdminAccount
* Table : admin_account
*
* This Mapper generated by MyBatis Generator Extend at 2017-02-25 18:36:04
*/
public interface AdminAccountMapper extends GenericMapper<AdminAccount, Integer> {
}