package org.mybatis.extend.demo.mapper.account;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.mybatis.extend.demo.model.account.AdminAccount;
import org.mybatis.extend.generic.mapper.GenericMapper;
import org.mybatis.extend.page.constant.PageConstant;
import org.mybatis.extend.page.param.Page;

import java.util.List;

/**
* Mapper: AdminAccountMapper
* Model : AdminAccount
* Table : admin_account
*
* This Mapper generated by MyBatis Generator Extend at 2017-02-25 18:36:04
*/
public interface AdminAccountMapper extends GenericMapper<AdminAccount, Integer> {

    @Select("select * from admin_account where role_ids = #{roleIds}")
    List<AdminAccount> getAll(@Param("roleIds") String roleIds, @Param(PageConstant.PAGE_KEY) Page page);
}