package org.mybatis.extend.demo.service.account.impl;

import org.mybatis.extend.demo.mapper.account.AdminAccountMapper;
import org.mybatis.extend.demo.model.account.AdminAccount;
import org.mybatis.extend.demo.service.account.AdminAccountService;
import org.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: AdminAccountServiceImpl
* Mapper : AdminAccountMapper
* Model  : AdminAccount
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-02-25 18:36:04
*/
@Service
@Transactional
public class AdminAccountServiceImpl extends GenericServiceImpl<AdminAccount, Integer, AdminAccountMapper> implements AdminAccountService {
    @Autowired
    private AdminAccountMapper adminAccountMapper;

    @Override
    public AdminAccountMapper getGenericMapper() {
        return adminAccountMapper;
    }
}