package org.mybatis.extend.demo.service.role.impl;

import org.mybatis.extend.demo.mapper.role.AdminRoleMapper;
import org.mybatis.extend.demo.model.role.AdminRole;
import org.mybatis.extend.demo.service.role.AdminRoleService;
import org.mybatis.extend.generic.service.impl.GenericServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: AdminRoleServiceImpl
* Mapper : AdminRoleMapper
* Model  : AdminRole
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-02-25 18:36:04
*/
@Service
@Transactional
public class AdminRoleServiceImpl extends GenericServiceImpl<AdminRole, Integer, AdminRoleMapper> implements AdminRoleService {
    @Autowired
    private AdminRoleMapper adminRoleMapper;

    @Override
    public AdminRoleMapper getGenericMapper() {
        return adminRoleMapper;
    }
}